- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-ironic-bfv from old job gate-tempest-dsvm-ironic-bfv-ubuntu-xenial
  tasks:

    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo
